services:

  backend:
    container_name: audience-allocation-backend
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - nginx_network
    environment:
      - MODE=local
    depends_on:
      - redis
    volumes:
      - ./config.yaml:/config.yaml
    command: >
      bash -c "python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn backend.wsgi:application --bind 0.0.0.0:8080 --timeout 120"


  frontend:
    container_name: audience-allocation-frontend
    build: ./frontend
    ports:
      - "8000:8000"
    volumes:
      - static-data:/frontend/static
      - ./config.yaml:/config.yaml
    networks:
      - nginx_network
    environment:
      - MODE=local
    depends_on:
      - backend
    entrypoint: /entrypoint.sh
    command: >
      bash -c "gunicorn frontend.wsgi:application --bind 0.0.0.0:8000 --timeout 120"


  tg-bot:
    container_name: audience-allocation-tg-bot
    build: ./tg-bot
    environment:
      - MODE=local
    volumes:
      - ./config.yaml:/config.yaml
    depends_on:
      - backend


  redis:
    container_name: audience-allocation-redis
    image: redis:7-alpine
    networks:
      - nginx_network
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 3


  celery:
    container_name: audience-allocation-celery
    build: ./backend
    networks:
      - nginx_network
    environment:
      - MODE=local
    depends_on:
      - backend
      - redis
    volumes:
      - ./config.yaml:/config.yaml
    command: >
      celery -A backend worker --loglevel=info


volumes:
  static-data:
    external: true

networks:
  nginx_network:
    external: true







# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     users: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt
